### PR TITLE
Modernize and introduce new statuses

### LINKED ISSUE #8: Add support for more UPS statuses
Currently (v0.70) WMNut only supports a few device status values, namely `OL`, `OB`, `LB`, `OVER`(loaded):
* https://github.com/networkupstools/wmnut/blob/e3255f724d6b75541fce6c07d9ceba6246d05d72/src/wmnut.h#L78-L85
* https://github.com/networkupstools/wmnut/blob/e3255f724d6b75541fce6c07d9ceba6246d05d72/src/wmnut.c#L130-L151
* https://github.com/networkupstools/wmnut/blob/e3255f724d6b75541fce6c07d9ceba6246d05d72/src/wmnut.c#L344-L435

Recent years of evolution on NUT side added many more values, see https://github.com/networkupstools/nut/blob/master/clients/status.h and https://github.com/networkupstools/nut/blob/master/clients/upsmon.h -- such as "administrative OFF", "administrative bypass", "calibration", "trim/boost", and recently "ECO mode" in https://github.com/networkupstools/nut/pull/2637 - would be nice to reflect those in the widget.

### LINKED ISSUE #9: Overload and non-parsed status processing is failing
`OVER` and non-processed statuses never get evaluated as there is a bug in the `LB` status evaluation within this function:

https://github.com/networkupstools/wmnut/blob/e3255f724d6b75541fce6c07d9ceba6246d05d72/src/wmnut.c#L136-L150

This `else if` checks if `LB` is `not contained` and sets the status to `UPS_LOWBATT`, but should check if it `is contained` here:

https://github.com/networkupstools/wmnut/blob/e3255f724d6b75541fce6c07d9ceba6246d05d72/src/wmnut.c#L142

I'm overhauling this function as part of a larger pull request in the works (#8), so this issue is mostly a reminder to myself.

### PR DESCRIPTION
**Pull request by desertwitch**
This pull request addresses the issues #8 and #9, as well as a compiler warning.
The status handling was modernized to graphically visualize (including combinations of) these statuses:
```
#define ST_ONLINE      (1 << 0)	/* UPS is on line */
#define ST_ONBATT      (1 << 1)	/* UPS is on battery */
#define ST_LOWBATT     (1 << 2)	/* UPS is on low battery */
#define ST_FSD         (1 << 3)	/* UPS is shutting down */
#define ST_REPLBATT    (1 << 4)	/* UPS battery needs replacement */
#define ST_CAL         (1 << 5)	/* UPS is calibrating */
#define ST_OFF         (1 << 6)	/* UPS is (administratively) offline */
#define ST_BYPASS      (1 << 7)	/* UPS is on bypass */
#define ST_OVERLOAD    (1 << 8)	/* UPS is overloaded */
#define ST_TRIM        (1 << 9)	/* UPS is trimming */
#define ST_BOOST       (1 << 10)	/* UPS is boosting */
#define ST_ALARM       (1 << 11)	/* UPS has active alarm(s) */
```
The (graphical) visualization of the various statuses can be looked at here: [wmnut-pr.pdf](https://github.com/user-attachments/files/17461005/wmnut-pr.pdf)

More (not road-blocking) issues outside the scope of this PR have been discovered (and will be logged into "Issues") with further work possible for a prospective new version. This could include removal of unused legacy arguments and internal code remnants e.g. for previous beep/alert functions that are no longer in the codebase even before this PR (and `upsmon` being better equipped and integrated for handling notifications nowadays, when compared to 12 years ago). More importantly improvements to ensure more graceful client retrying/reconnections on staleness/connection loss not requiring widget restart.

fixes #8, fixes #9

### CODE REVIEW

File: src/wmnut.c [hunk 1]
```diff
@@ -131,23 +148,25 @@ void get_ups_info(void)
...
-			CurHost->ups_status = UPS_ONLINE;
-		else if (!strncmp(value, "OB", 2))
-			CurHost->ups_status = UPS_ONBATT;
-		else if (!strstr(value, "LB"))
-			CurHost->ups_status = UPS_LOWBATT;
-		else if (!strncmp(value, "OVER", 4))
-			CurHost->ups_status = UPS_OVERLOAD;
-		else
-		CurHost->ups_status = UPS_DEFAULT;
+		if (strstr(value, "OL")) {
```
Comment (jimklimov) [inline src/wmnut.c:155]: Currently we are lucky that no keyword in the table we care about is a sub-string of another. This was not really a consideration for NUT standard (`nut-names.txt`) and technically drivers or NUT forks can make up their own words although it is frowned upon.

Generally I'd be in favor of porting https://github.com/networkupstools/nut/blob/8becada220ceb8e2634c4e11cc7bc4d2f922fbd8/common/common.c#L2068 `str_contains_token()` (or maybe exposing it in `libupsclient`, to avoid duplication?) so some contrived `ups.status="LOBOTOMIZED"` would not match `OB` as a sub-string.

Comment (jimklimov) [reply src/wmnut.c:155]: Should be addressed by https://github.com/networkupstools/nut/pull/2859 (to be available since NUT v2.8.3).

Comment (desertwitch) [reply src/wmnut.c:155]: Good point, mostly ported over the existing logic from NUT at that time (iirc), but definitely makes sense and nicely implemented in subsequent commits as usual. 👍
